import { ArrowLeft, ArrowRight, ShoppingCart } from "lucide-react";
import Footer from "./Footer";
import "./EcommerceArticle.css";
import heroImage from "../assets/blogs/e commerce hero image.webp";
import cartImage from "../assets/blogs/e commerce artical cart.webp";
import personImage from "../assets/blogs/every screen man image.webp";
const toc=[["design","A Clean & Professional Design"],["product-pages","High-Quality Product Pages"],["checkout","A Smooth & Secure Checkout"],["mobile","Mobile-Friendly Experience"],["trust","Trust Elements"],["marketing","Marketing & Retargeting"],["final-thoughts","Final Thoughts"]];
const related=[{title:"Why Your Website Gets Visitors but No Customers",category:"Web Development",time:"6 min read",image:"featured-website.webp",path:"/blog/website-conversion"},{title:"5 Website Mistakes That Make Your Business Look Unprofessional",category:"Web Development",time:"4 min read",image:"website-mistakes.webp",path:"/blog/website-mistakes"},{title:"UI/UX Design: Why Good Design Is More Than Just Pretty",category:"UI/UX Design",time:"5 min read",image:"uiux-designs.webp",path:"/blog/ui-ux-design"},{title:"How Social Media Can Actually Grow Your Business",category:"Social Media",time:"6 min read",image:"socialmedia.webp",path:"/blog/social-media-growth"}];
const blogImages=import.meta.glob("../assets/blogs/*.webp",{eager:true,import:"default"});
function navigate(e,path,onNavigate){e.preventDefault();onNavigate(path)}
function Tip(){return <div className="ecom-tip"><ShoppingCart size={16} fill="currentColor"/><span><b>Tip:</b> Use a clean design with clear categories and a simple navigation menu.</span></div>}
function Quote(){return <div className="ecom-quote"><strong>“</strong><b>A smooth checkout process turns interested visitors into loyal customers.</b><span>— 404 Solutions</span></div>}
export default function EcommerceArticle({onOpenContact,onNavigate}){return <><div className="ecom-page"><div className="ecom-container"><button className="ecom-back" type="button" onClick={e=>navigate(e,"/blog",onNavigate)}><ArrowLeft size={15}/> Back to Blog</button><div className="ecom-layout"><main className="ecom-main"><header className="ecom-header"><span className="ecom-category">DIGITAL GROWTH</span><h1>E-Commerce Website:<br/>What Your Store <em>Needs to Convert</em></h1><p>An e-commerce website is more than just a product listing — it’s a complete shopping experience. In this article, we’ll explore the key elements your online store needs to turn visitors into customers.</p></header><img className="ecom-hero" src={heroImage} alt="More than a store, a better shopping experience"/><article className="ecom-content">
<section id="design"><div className="ecom-heading"><i>1</i><h2>A Clean &amp; Professional Design</h2></div><p>Your store’s design creates the first impression. A clean, modern, and easy-to-navigate layout builds trust and helps customers find what they need quickly.</p><Tip/></section>
<section id="product-pages"><div className="ecom-heading"><i>2</i><h2>High-Quality Product Pages</h2></div><p>Good product pages include high-quality images, clear descriptions, pricing, reviews, and relevant product details. The more information you provide, the more confident customers feel.</p></section>
<section id="checkout"><div className="ecom-heading"><i>3</i><h2>A Smooth &amp; Secure Checkout</h2></div><p>A complicated checkout process can make customers abandon their cart. Keep it simple, offer multiple payment options, and ensure your site is secure (HTTPS).</p><Quote/></section>
<section id="mobile"><div className="ecom-heading"><i>4</i><h2>Mobile-Friendly Experience</h2></div><p>Many customers shop from their phones. A mobile-optimized store ensures a smooth shopping experience on all devices.</p></section>
<section id="trust"><div className="ecom-heading"><i>5</i><h2>Trust Elements</h2></div><p>Display customer reviews, testimonials, trust badges, return policies, and secure payment logos to build credibility and reduce hesitation.</p></section>
<section id="marketing"><div className="ecom-heading"><i>6</i><h2>Marketing &amp; Retargeting</h2></div><p>Use email marketing, discounts, and retargeting ads to bring back visitors and increase sales. Keep your customers engaged even after they’ve visited your store.</p></section>
<section id="final-thoughts" className="ecom-final"><h2>Final Thoughts</h2><p>A successful e-commerce website is not just about selling products — it’s about creating a seamless, trustworthy, and enjoyable shopping experience. Focus on the right elements, keep improving, and your online store can grow into a powerful revenue channel.</p></section>
<section className="ecom-bottom-cta"><img src={personImage} alt="Person ready to build an online store"/><div><h2>Ready to Build Your<br/>E-Commerce Store?</h2><p>Let’s create a high-converting online store for your business.</p></div><button type="button" onClick={onOpenContact}>Start a Project <ArrowRight size={15}/></button></section></article></main><aside className="ecom-sidebar"><div className="ecom-card ecom-toc"><h2>Table of Contents</h2><ol>{toc.map(([id,title],i)=><li className={i===0?"active":""} key={id}><a href={`#${id}`}>{i+1}. &nbsp;{title}</a></li>)}</ol></div><div className="ecom-newsletter"><h2>Get more insights like this<br/>straight to your inbox.</h2><form onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="ecom-email">Email address</label><input id="ecom-email" type="email" placeholder="Enter your email"/><button type="submit" aria-label="Subscribe"><ArrowRight size={16}/></button></form></div><div className="ecom-card ecom-related"><h2>Related Articles</h2><div>{related.map(a=><a href={a.path} key={a.path} onClick={e=>navigate(e,a.path,onNavigate)}><img src={blogImages[`../assets/blogs/${a.image}`]} alt=""/><span><b>{a.title}</b><small>{a.category}<br/>{a.time}</small></span></a>)}</div><a className="ecom-view-all" href="/blog" onClick={e=>navigate(e,"/blog",onNavigate)}>View All Articles <ArrowRight size={15}/></a></div><div className="ecom-card ecom-sidebar-quote"><strong>“</strong><blockquote>A great online store doesn’t just sell products, it builds relationships and creates long-term opportunities.</blockquote><cite>— 404 Solutions</cite><i/><img src={cartImage} alt="Online store cart"/></div></aside></div></div></div><Footer onOpenContact={onOpenContact}/></>}
