import { motion } from "framer-motion";
import { Activity, ArrowRight, BarChart3, Check, Code2, Compass, FileText, Megaphone, MoreHorizontal, PenTool, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import heroArtwork from "../assets/services/service page hero.webp";
import impactArtwork from "../assets/services/service page lets turn your ideas into impact robot.webp";
import "./ServicesPage.css";

const services = [
  ["Web Development", "Modern, high-performance websites built for speed, security, and growth.", ["Custom Websites", "E-commerce Solutions", "CMS Development"], Code2],
  ["UI/UX Design", "User-centered designs that make your brand memorable.", ["UI/UX for Web & Mobile", "Prototyping & Wireframes", "Design Systems"], PenTool],
  ["SEO & Digital Growth", "Get discovered, drive traffic, and turn visitors into customers.", ["On-Page & Off-Page SEO", "Keyword Strategy", "Growth Consulting"], BarChart3],
  ["Social Media Marketing", "Build your brand presence and engage your audience.", ["Content Strategy", "Social Media Management", "Paid Campaigns"], Megaphone],
  ["Branding & Identity", "Create a unique identity that connects and converts.", ["Logo & Visual Identity", "Brand Strategy", "Marketing Collateral"], Sparkles],
  ["Other Services", "Need something custom? We're just a conversation away.", ["Consultation", "Maintenance & Support", "Custom Solutions"], MoreHorizontal],
];
const process = [["01", "Discover", "We understand your goals.", Search], ["02", "Plan", "We create a custom strategy.", FileText], ["03", "Build", "We design and develop.", Activity], ["04", "Grow", "We optimize for long-term success.", BarChart3]];
const features = [["Strategic Approach", "Solutions tailored to your goals.", Compass], ["End-to-End Support", "From idea to execution.", Sparkles], ["Real Results", "Built for long-term growth.", UsersRound]];

export default function ServicesPage({ onOpenContact }) {
  return <div className="services-page">
    <section className="services-hero" aria-labelledby="services-page-title"><div className="services-shell services-hero-grid">
      <motion.div className="services-hero-copy" initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.55 }}><p className="services-eyebrow">Our Services</p><h1 id="services-page-title">Digital Solutions<br />for <span>Real Growth.</span></h1><p className="services-lead">From websites to brand growth, we provide end-to-end digital solutions that help businesses stand out, connect, and grow.</p><div className="services-features">{features.map(([title, text, Icon]) => <div className="services-feature" key={title}><span><Icon size={22} /></span><div><strong>{title}</strong><small>{text}</small></div></div>)}</div></motion.div>
      <motion.div className="services-hero-art" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.1 }}><div className="services-art-glow" aria-hidden="true" /><img src={heroArtwork} alt="404 Solutions robot presenting digital services" width="1575" height="999" fetchPriority="high" /></motion.div>
    </div></section>
    <section className="services-offer services-shell" aria-labelledby="offer-title"><div className="services-section-heading"><p className="services-eyebrow">What We Offer</p><h2 id="offer-title">Our Services</h2><p>Everything you need to build, grow, and scale your business online.</p></div><div className="services-actions"><button type="button" className="services-ghost" onClick={onOpenContact}>Custom Solution?</button><button type="button" className="services-primary" onClick={onOpenContact}>Let&rsquo;s Discuss <ArrowRight size={16} /></button></div></section>
    <section className="services-cards services-shell" aria-label="Services we offer">{services.map(([title, description, items, Icon], index) => <motion.article className="service-card" key={title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ delay: index * 0.05 }}><div className="service-icon"><Icon size={30} /></div><h3>{title}</h3><p>{description}</p><ul>{items.map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul><button type="button" aria-label={`Learn more about ${title}`} onClick={onOpenContact}><ArrowRight size={16} /></button></motion.article>)}</section>
    <section className="services-process services-shell" aria-labelledby="process-title"><div className="process-intro"><p className="services-eyebrow">Our Process</p><h2 id="process-title">A Simple Path to Success</h2><p>We keep things simple, transparent, and focused on results.</p></div><div className="process-steps">{process.map(([number, title, text, Icon], index) => <div className="process-step" key={title}><div className="process-icon"><Icon size={27} /></div><b>{number}</b><h3>{title}</h3><p>{text}</p>{index < process.length - 1 && <ArrowRight className="process-arrow" size={20} />}</div>)}</div></section>
    <section className="services-why services-shell" aria-labelledby="why-title"><div className="services-impact-art"><div className="services-art-glow" aria-hidden="true" /><img src={impactArtwork} alt="404 Solutions robot turning ideas into impact" width="1460" height="1077" loading="lazy" /></div><div className="services-why-copy"><p className="services-eyebrow">Why Choose Us</p><h2 id="why-title">More Than Just a Service.<br /><span>A True Partner.</span></h2><p>We combine creativity, technology, and strategy to deliver digital solutions that actually make a difference.</p><div className="why-checks">{["Client-Focused Approach", "On-Time Delivery", "Transparent Communication", "Long-Term Support"].map((item) => <span key={item}><Check size={16} />{item}</span>)}</div></div><div className="services-stats">{[["50+", "Projects Delivered", BarChart3], ["30+", "Happy Clients", UsersRound], ["98%", "Client Satisfaction", ShieldCheck], ["5+", "Industries Served", Sparkles]].map(([value, label, Icon]) => <div key={label}><Icon size={22} /><strong>{value}</strong><small>{label}</small></div>)}</div></section>
  </div>;
}
